#############################################################################
# Makefile for building: FindAbiturients
# Generated by qmake (3.0) (Qt 5.0.2) on: ?? 18. ??? 09:18:08 2013
# Project:  FindAbiturients.pro
# Template: app
# Command: D:\Qt\qtbase\bin\qmake.exe -spec win32-msvc2012 -o Makefile FindAbiturients.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:\Qt\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: FindAbiturients.pro D:\Qt\qtbase\mkspecs\win32-msvc2012\qmake.conf D:\Qt\qtbase\mkspecs\features\spec_pre.prf \
		D:\Qt\qtbase\mkspecs\common\shell-win32.conf \
		D:\Qt\qtbase\mkspecs\qconfig.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_axbase.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_axcontainer.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_axserver.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_bootstrap.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_clucene.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_concurrent.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_core.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_designer.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_designercomponents.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_gui.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_help.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_multimedia.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_network.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_opengl.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_platformsupport.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_printsupport.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_qml.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_qmldevtools.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_qmltest.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_quick.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_quickparticles.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_script.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_scripttools.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_sql.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_svg.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_testlib.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_uitools.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_v8.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_widgets.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_xml.pri \
		D:\Qt\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri \
		D:\Qt\qtbase\mkspecs\features\qt_functions.prf \
		D:\Qt\qtbase\mkspecs\features\qt_config.prf \
		D:\Qt\qtbase\mkspecs\win32-msvc2012\qmake.conf \
		D:\Qt\qtbase\mkspecs\features\spec_post.prf \
		D:\Qt\qtbase\mkspecs\features\exclusive_builds.prf \
		D:\Qt\qtbase\mkspecs\features\default_pre.prf \
		D:\Qt\qtbase\mkspecs\features\win32\default_pre.prf \
		D:\Qt\qtbase\mkspecs\features\resolve_config.prf \
		D:\Qt\qtbase\mkspecs\features\default_post.prf \
		D:\Qt\qtbase\mkspecs\features\win32\rtti.prf \
		D:\Qt\qtbase\mkspecs\features\warn_on.prf \
		D:\Qt\qtbase\mkspecs\features\qt.prf \
		D:\Qt\qtbase\mkspecs\features\resources.prf \
		D:\Qt\qtbase\mkspecs\features\moc.prf \
		D:\Qt\qtbase\mkspecs\features\win32\opengl.prf \
		D:\Qt\qtbase\mkspecs\features\uic.prf \
		D:\Qt\qtbase\mkspecs\features\win32\windows.prf \
		D:\Qt\qtbase\mkspecs\features\testcase_targets.prf \
		D:\Qt\qtbase\mkspecs\features\exceptions.prf \
		D:\Qt\qtbase\mkspecs\features\yacc.prf \
		D:\Qt\qtbase\mkspecs\features\lex.prf \
		FindAbiturients.pro \
		D:/Qt/qtbase/lib/Qt5Widgets.prl \
		D:/Qt/qtbase/lib/Qt5Network.prl \
		D:/Qt/qtbase/lib/Qt5Gui.prl \
		D:/Qt/qtbase/lib/Qt5Core.prl
	$(QMAKE) -spec win32-msvc2012 -o Makefile FindAbiturients.pro
D:\Qt\qtbase\mkspecs\features\spec_pre.prf:
D:\Qt\qtbase\mkspecs\common\shell-win32.conf:
D:\Qt\qtbase\mkspecs\qconfig.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_axbase.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_axcontainer.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_axserver.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_bootstrap.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_clucene.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_core.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_designer.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_designercomponents.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_gui.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_help.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_multimedia.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_network.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_opengl.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_platformsupport.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_qml.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_qmldevtools.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_qmltest.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_quick.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_quickparticles.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_script.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_scripttools.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_sql.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_svg.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_testlib.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_uitools.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_v8.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_widgets.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_xml.pri:
D:\Qt\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri:
D:\Qt\qtbase\mkspecs\features\qt_functions.prf:
D:\Qt\qtbase\mkspecs\features\qt_config.prf:
D:\Qt\qtbase\mkspecs\win32-msvc2012\qmake.conf:
D:\Qt\qtbase\mkspecs\features\spec_post.prf:
D:\Qt\qtbase\mkspecs\features\exclusive_builds.prf:
D:\Qt\qtbase\mkspecs\features\default_pre.prf:
D:\Qt\qtbase\mkspecs\features\win32\default_pre.prf:
D:\Qt\qtbase\mkspecs\features\resolve_config.prf:
D:\Qt\qtbase\mkspecs\features\default_post.prf:
D:\Qt\qtbase\mkspecs\features\win32\rtti.prf:
D:\Qt\qtbase\mkspecs\features\warn_on.prf:
D:\Qt\qtbase\mkspecs\features\qt.prf:
D:\Qt\qtbase\mkspecs\features\resources.prf:
D:\Qt\qtbase\mkspecs\features\moc.prf:
D:\Qt\qtbase\mkspecs\features\win32\opengl.prf:
D:\Qt\qtbase\mkspecs\features\uic.prf:
D:\Qt\qtbase\mkspecs\features\win32\windows.prf:
D:\Qt\qtbase\mkspecs\features\testcase_targets.prf:
D:\Qt\qtbase\mkspecs\features\exceptions.prf:
D:\Qt\qtbase\mkspecs\features\yacc.prf:
D:\Qt\qtbase\mkspecs\features\lex.prf:
FindAbiturients.pro:
D:/Qt/qtbase/lib/Qt5Widgets.prl:
D:/Qt/qtbase/lib/Qt5Network.prl:
D:/Qt/qtbase/lib/Qt5Gui.prl:
D:/Qt/qtbase/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2012 -o Makefile FindAbiturients.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) FindAbiturients.exp
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
